############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Services"
# pageRef = "/our_services"
weight = 2

[[main]]
parent = "Services"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Services"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Services"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Services"
name = "Categories"
pageRef = "/categories"

[[main]]
name = "About"
pageRef = "/about"
weight = 3

[[main]]
name = "Elements"
pageRef = "/elements"
weight = 4

[[main]]
name = "Pages"
weight = 5

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Services"
pageRef = "/services"
weight = 2

[[footer]]
name = "Elements"
pageRef = "/all_elements"
weight = 3

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 4
