baseURL: https://www.hugobricks.preview.usecue.com
theme: hugobricks
defaultContentLanguage: en
assetDir: static
math: true

services:
  googleAnalytics:
    id: "G-7SDG43FBQT"

  markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
  fr:
    languageName: Français
    contentDir: content/fr
    weight: 2
    disabled: true
